name: deploy

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

jobs:
  push-to-gh-pages:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^7.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 安装依赖
      - name: Install dependencies
        run: pnpm install
      # 打包
      - name: Build Packages
        run: pnpm run build

      - name: deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzh
          path: docs/.vuepress/dist/
          remote_path: /data_prod/webapp/lamp-doc/dist/
          remote_host: ${{ secrets.MY_CENTOS_HOST }}
          remote_port: ${{ secrets.MY_CENTOS_PORT }}
          remote_user: ${{ secrets.MY_CENTOS_USERNAME }}
          remote_key: ${{ secrets.MY_CENTOS_RSA_PRIVATE_KEY }}
